server:
  port: 3333
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/morning_db?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MoHikariPool
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    # 没有密码留空
    password:
#  rabbitmq:
#    host: 192.168.73.130
#    port: 5672
#    username: choxsu
#    password: choxsu-pwd
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    port: 465
    username: choxsu@163.com
    password: -------  # 授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
# 开发环境下，配置mybatis的sql打印配置
logging:
  level:
    com.syc.service.dao: debug