server:
  port: 3333
  undertow:
    accesslog:
      enabled: false
spring:
  profiles:
    active: dev
  application:
    name: morning
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    suffix: .html


mybatis-plus:
  configuration:
    log-prefix: mo
  global-config:
    db-config:
      id-type: auto
