server:
  port: 3334
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sblog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password: choxsu-redis-pwd
#  rabbitmq:
#    host: 192.168.73.130
#    port: 5672
#    username: choxsu-admin
#    password: choxsu-admin-pwd@su
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    port: 465
    username: choxsu@163.com
    password: ---------  # 授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
# 开发环境下，配置mybatis的sql打印配置
logging:
  level:
    com.syc.service.dao: debug